---
- name: Aprovisionar Runner Ubuntu para Azure DevOps
  hosts: runner
  become: yes
  tasks:

    - name: Descargar el paquete del agente de Azure DevOps
      ansible.builtin.get_url:
        url: https://vstsagentpackage.azureedge.net/agent/3.242.1/vsts-agent-linux-x64-3.242.1.tar.gz
        dest: /home/runner/vsts-agent-linux-x64-3.242.1.tar.gz

    - name: Extraer el archivo del agente
      ansible.builtin.command:
        cmd: tar -xzf vsts-agent-linux-x64-3.242.1.tar.gz
        chdir: /home/runner
      

    - name: Ejecutar el script de configuración (Aceptando licencia y configurando el agente)
      become: no
      ansible.builtin.expect:
        command: ./config.sh
        chdir: /home/runner/
        responses:
          'Enter (Y/N) Accept the Team Explorer Everywhere license agreement now? (press enter for N)': 'y\n'
          'Enter server URL': 'https://dev.azure.com/SEGA-AIT\n'
          'Enter authentication type (press enter for PAT)': '\n'
          'Enter personal access token': 'rse7lkypndp4j73phvgr6npfeb3zt4bypu3luueddumvkczkus6a\n'
          'Enter agent pool (press enter for default)': 'runner\n'
          'Enter agent name (press enter for myvm-1)': 'runner\n'
          'Enter work folder (press enter for _work)': 'runner\n'

    - name: Instalar el servicio del agente
      become: no
      ansible.builtin.command:
        cmd: sudo ./svc.sh install
        chdir: /home/runner/

    - name: Iniciar el servicio del agente
      become: no
      ansible.builtin.command:
        cmd: sudo ./svc.sh start
        chdir: /home/runner/
